#!/usr/bin/env bash
# Tool Name :- IPX
# Author :- Aayush_xid_su
# Date :- 10/12/2024

case "$1" in
  -m)
    php modules/.tracx.php
  ;;
  -t)
    case "$#" in
    2)
      php modules/.tracax.php $2
    ;;
    *)
      echo "error : invalid arguments !!"
      echo "use: ipx -t <target_ip>"
    ;;
    esac
  ;;
  -u)
    php modules/.update.php
    exit
  ;;
  update)
    php modules/.update.php
    exit
  ;;
  start)
    php .IPX.php
    exit
  ;;
  -rm)
    php modules/.uninstall.php
    exit
  ;;
  *)
    echo "Usage: ipX [command]... [arguments]..."
    echo " Commands:"
    echo " -t <target_ip>      to trace target ip."
    echo " -m                  to trace your own ip."
    echo " -h                  to show help."
    echo " -u                  to update ipx."
    echo " help                to show help."
    echo " update              to update ipx."
    echo " start               to start ipx menu."
esac
